language: c

before_script:
  - git submodule update --init
  - ./buildrump.sh/buildrump.sh -s rumpsrc -o rumpobj -V MKSTATICLIB=no -q -j4 checkout fullbuild

script:
  - export LDFLAGS='-Lrump/lib -Wl,-Rrump/lib'
  - export CPPFLAGS='-Irump/include'
  - ./configure
  - make
  - ./fsu_cat -t sysvbfs buildrump.sh/tests/fstest_img/sysvbfs_le.img ./README | grep 'Is that a small file system'

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
